version: "3.6"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /homeassistant/data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      general:
        ipv4_address: 10.0.0.200

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    volumes:
      - ./nginxproxymanager/data:/data
      - ./letsencrypt:/etc/letsencrypt

    networks:
      general:
        ipv4_address: 10.0.0.201

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'

    volumes:
      - './pihole/data:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'

    restart: unless-stopped
    networks:
      general:
        ipv4_address: 10.0.0.202

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Istanbul
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    restart: always
    networks:
      general:
        ipv4_address: 10.0.0.203

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    depends_on:
      - wireguard
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Istanbul
      - TRANSMISSION_WEB_HOME=/transmissionic/
      - USER=phyesix
      - PASS=phyesix
      - PEERPORT=54914
    volumes:
      - ./transmission/transmission-config:/config
      - /media/nas/torrent/downloads:/downloads
      - /media/nas/torrent/watch:/watch
    restart: always
    network_mode: "service:wireguard"

networks:
  general:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24