version: "3.6"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - eyJhIjoiOTQzNWM4YmE0ZTkxOTY3YzNkYjdmOGQ2YTIzZTE0OGYiLCJ0IjoiN2VmMTBlMzktNTU1Yy00YzM1LWEwNDMtYWQ1YWI3MDRjYmU4IiwicyI6IkxFcHVXVmdVVG5HNnJHZ2JqTHJqaUxGUWpUaVFmUmdwN3kraVFWakFtNlk9In0=

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ./mqtt/mosquitto-data:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
    networks:
      cnetwork:
        ipv4_address: 10.100.5.10

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Istanbul
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      cnetwork:
        ipv4_address: 10.100.5.11

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./homeassistant/data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      cnetwork:
        ipv4_address: 10.100.5.12

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    privileged: true
    networks:
      cnetwork:
        ipv4_address: 10.100.5.13

  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 853:853/udp
      - 784:784/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./adguard/data/work:/opt/adguardhome/work
      - ./adguard/data/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.14

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ./portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.15

  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - ./homebox/data:/data/
    ports:
      - 7745:7745
    networks:
      cnetwork:
        ipv4_address: 10.100.5.16

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./calibre/data:/config
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.17

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./calibre-web/data:/config
      - hdd:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.18

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - CLI_ARGS=--no-hosted-server#optional
    volumes:
      - ./duplicati/data/config:/config
      - ./duplicati/data/backups:/backups
      - ./duplicati/data/source:/source
      - /root/docker:/dockerfiles
    ports:
      - 8200:8200
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.19

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/data/config:/config
      - hdd:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.20

  jdownloader-2:
    container_name: jdownloader-2
    image: jlesage/jdownloader-2
    environment:
      - TZ=Europe/Istanbul
      - VNC_PASSWORD=storax206
    ports:
      - 5800:5800
    volumes:
      - ./jdownloader-2:/config
      - hdd:/output
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.21

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - JELLYFIN_PublishedServerUrl=10.0.5.22 #optional
    volumes:
      - ./jellyfin/data:/config
      - hdd:/data/tvshows
      - hdd:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.22

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./lidarr/data/config:/config
      - hdd:/music #optional
      - hdd:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.23

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.24

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./radarr/data:/config
      - hdd:/movies #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.25

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./sonarr/data:/config
      - hdd:/tv #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.26

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./bazarr/data/config:/config
      - hdd:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.27

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./readarr/data:/config
      - ./readarr/books:/books
      - ./readarr/downloadclient-downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.28

  feedropolis:
    container_name: feedropolis
    image: schklom/feedropolis
    depends_on:
      - pg_db
    ports:
      - 3000:3000
    privileged: true
    environment:
      - DATABASE_URL=postgres://pgdbuser:pgdbpassword@pg_db:5432/pgdb
      #- BASE_URL=http://10.100.1.30:3000
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.29

  rssbridge:
    container_name: rssbridge
    image: rssbridge/rss-bridge
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./rssbridge:/config
    networks:
      cnetwork:
        ipv4_address: 10.100.5.30

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    depends_on:
      - pg_db
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=pg_db
      - DB_PORT=5432
      - DB_DATABASE=pgdb
      - DB_USERNAME=pgdbuser
      - DB_PASSWORD=pgdbpassword
      - TZ=Europe/Istanbul
      - APP_NAME="Natura Cakirlar Superonline"
      - PUBLIC_DASHBOARD=true
      - TELEGRAM_BOT_TOKEN=6959957676:AAHDJ3-xnjG425N7Bp_HlkAgvWqTVEpyUcM
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./speedtest-tracker:/config
      - ./speedtest-tracker/web:/etc/ssl/web
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.31
  
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - CONTEXT_PATH= #optional
      - JAVA_OPTS= #optional
    volumes:
      - ./airsonic-advanced/airsonic-advanced/config:/config
      - ./airsonic-advanced/music:/music
      - ./airsonic-advanced/playlists:/playlists
      - ./airsonic-advanced/podcasts:/podcasts
      - ./airsonic-advanced/other media:/media #optional
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.32

  apprise-api:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./apprise-api/config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.33

  booksonic-air:
    image: lscr.io/linuxserver/booksonic-air:latest
    container_name: booksonic-air
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      #- CONTEXT_PATH=url-base #optional
    volumes:
      - ./booksonic-air/booksonic-air/config:/config
      - ./booksonic-air/audiobooks:/audiobooks
      - ./booksonic-air/podcasts:/podcasts
      - ./booksonic-air/othermedia:/othermedia
    ports:
      - 4040:4040
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.34

  spotube:
    image: lscr.io/linuxserver/spotube:latest
    container_name: spotube
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./spotube/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.35

  headphones:
    image: lscr.io/linuxserver/headphones:latest
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./headphones/appdata/config:/config
      - ./headphones/downloads:/downloads
      - ./headphones/music:/music
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.36

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./nextcloud/nextcloud/config:/config
      - ./nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.37

  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - SECRET_PATH=/pwndrop
    volumes:
      - ./pwndrop/appdata:/config
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.38

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./syncthing/syncthing/config:/config
      - ./syncthing/data1:/data1
      - ./syncthing/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.39

  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./ubooquity/ubooquity/data:/config
      - ./ubooquity/books:/books
      - ./ubooquity/comics:/comics
      - ./ubooquity/raw/files:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.40

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    depends_on:
      browser-chrome:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- BASE_URL= #optional
      - WEBDRIVER_DRIVER_URL=http://browser-chrome:4444/wd/hub
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/
      - FETCH_WORKERS=3
    volumes:
      - ./changedetection/config:/config
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.41

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/www:/srv/www
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.100

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - PASSWORD=storax206
      - SUDO_PASSWORD=storax206
      - PROXY_DOMAIN=code-server.nergiz.page #optional
      - DEFAULT_WORKSPACE=/config/workspace
      - DOCKER_MODS=linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-nvm
      - NODEJS_MOD_VERSION=20
    volumes:
      - ./code-server:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.101

  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ./chromium/config:/config
      - hdd:/config/hdd
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "4gb"
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.102

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - FIREFOX_CLI=https://www.ibrahimnergiz.com/ #optional
    volumes:
      - ./firefox/config:/config
      - hdd:/config/hdd
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "4gb"
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.103

  browser-chrome:
    container_name: browser-chrome
    hostname: browser-chrome
    image: seleniarm/standalone-chromium
    ports:
      -  4444:4444
    shm_size: '2gb'
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.104

  playwright-chrome:
    hostname: playwright-chrome
    container_name: playwright-chrome
    image: browserless/chrome
    restart: unless-stopped
    ports:
      - 1337:3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
    networks:
      cnetwork:
        ipv4_address: 10.100.5.105

  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - CONNECTION_TOKEN=storax206
      #- CONNECTION_SECRET=
      - SUDO_PASSWORD=storax206
      #- SUDO_PASSWORD_HASH=
    volumes:
      - ./openvscode-server/appdata/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      cnetwork:
        ipv4_address: 10.100.5.106

  pg_db:
    image: postgres:15
    container_name: pg_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=pgdbpassword
    volumes:
      - pg-db:/var/lib/postgresql/data
    networks:
      cnetwork:
        ipv4_address: 10.100.5.107

networks:
  cnetwork:
    name: cnetwork
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1

volumes:
  hdd:
    name: hdd
    driver: local
    driver_opts:
      type: ext4
      device: /dev/sda
      #o: bind
  pg-db: